<?php

namespace BcTic\CamIpalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends EntityRepository
{
	public function findChoicesOrderedByNumero()
    {
        $items =
             $this->getEntityManager()
            ->createQuery('SELECT c.id as id, c.nombre, c.numero , CAST(c.numero AS UNSIGNED) AS sortx FROM BcTicCamIpalBundle:Contrato c WHERE c.visible = 1 ORDER BY sortx ASC')
            ->getResult();

        $data = array();
        foreach ($items as $item) {
          $data[$item['id']] = '#'.$item['numero'].' '.$item['nombre'];
        }

        return $data;
    }

	
}
