<?php

namespace BcTic\CamIpalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObservacionDeComportamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionDeComportamientoRepository extends EntityRepository
{
}
