parameters:
    web_path: %kernel.root_dir%/../web
    aws_params:
        version: "%aws_version%"
        region: "%aws_region%"
        credentials: { key: "%aws_credentials_key%", secret: "%aws_credentials_secret%" }

    medioambiente_electrico_respuesta_13_1: 5
    medioambiente_electrico_respuesta_13_2: 5
    medioambiente_electrico_respuesta_13_3: 5
    medioambiente_electrico_respuesta_13_4: 50
    medioambiente_electrico_respuesta_13_5: 50
    medioambiente_electrico_respuesta_13_6: 10
    medioambiente_electrico_respuesta_13_7: 50
    medioambiente_electrico_respuesta_13_8: 50
    medioambiente_electrico_respuesta_13_9: 20
    medioambiente_electrico_respuesta_13_10: 10

    medioambiente_obras_civiles_respuesta_13_1: 5
    medioambiente_obras_civiles_respuesta_13_2: 5
    medioambiente_obras_civiles_respuesta_13_3: 5
    medioambiente_obras_civiles_respuesta_13_4: 50
    medioambiente_obras_civiles_respuesta_13_5: 10
    medioambiente_obras_civiles_respuesta_13_6: 5
    medioambiente_obras_civiles_respuesta_13_7: 10
    medioambiente_obras_civiles_respuesta_13_8: 50
    medioambiente_obras_civiles_respuesta_13_9: 5
    medioambiente_obras_civiles_respuesta_13_10: 20

    medioambiente_logistica_respuesta_13_1: 5
    medioambiente_logistica_respuesta_13_2: 5
    medioambiente_logistica_respuesta_13_3: 50
    medioambiente_logistica_respuesta_13_4: 10
    medioambiente_logistica_respuesta_13_5: 50
    medioambiente_logistica_respuesta_13_6: 5
    medioambiente_logistica_respuesta_13_7: 5
    medioambiente_logistica_respuesta_13_8: 10
    medioambiente_logistica_respuesta_13_9: 50
    medioambiente_logistica_respuesta_13_10: 20

    medioambiente_llvv_respuesta_13_1: 5
    medioambiente_llvv_respuesta_13_2: 5
    medioambiente_llvv_respuesta_13_3: 5
    medioambiente_llvv_respuesta_13_4: 50
    medioambiente_llvv_respuesta_13_5: 50
    medioambiente_llvv_respuesta_13_6: 10
    medioambiente_llvv_respuesta_13_7: 50
    medioambiente_llvv_respuesta_13_8: 5
    medioambiente_llvv_respuesta_13_9: 20
    medioambiente_llvv_respuesta_13_10: 10

    medioambiente_telecomunicaciones_respuesta_13_1: 0
    medioambiente_telecomunicaciones_respuesta_13_2: 0
    medioambiente_telecomunicaciones_respuesta_13_3: 0
    medioambiente_telecomunicaciones_respuesta_13_4: 0
    medioambiente_telecomunicaciones_respuesta_13_5: 0
    medioambiente_telecomunicaciones_respuesta_13_6: 0
    medioambiente_telecomunicaciones_respuesta_13_7: 0
    medioambiente_telecomunicaciones_respuesta_13_8: 0
    medioambiente_telecomunicaciones_respuesta_13_9: 0
    medioambiente_telecomunicaciones_respuesta_13_10: 0

    medioambiente_colombia_general_respuesta_13_1: 0
    medioambiente_colombia_general_respuesta_13_2: 0
    medioambiente_colombia_general_respuesta_13_3: 0
    medioambiente_colombia_general_respuesta_13_4: 0
    medioambiente_colombia_general_respuesta_13_5: 0
    medioambiente_colombia_general_respuesta_13_6: 0
    medioambiente_colombia_general_respuesta_13_7: 0
    medioambiente_colombia_general_respuesta_13_8: 0
    medioambiente_colombia_general_respuesta_13_9: 0
    medioambiente_colombia_general_respuesta_13_10: 0

    medioambiente_brazil_general_respuesta_13_1: 0
    medioambiente_brazil_general_respuesta_13_2: 0
    medioambiente_brazil_general_respuesta_13_3: 0
    medioambiente_brazil_general_respuesta_13_4: 0
    medioambiente_brazil_general_respuesta_13_5: 0
    medioambiente_brazil_general_respuesta_13_6: 0
    medioambiente_brazil_general_respuesta_13_7: 0
    medioambiente_brazil_general_respuesta_13_8: 0
    medioambiente_brazil_general_respuesta_13_9: 0
    medioambiente_brazil_general_respuesta_13_10: 0

    medioambiente_chilectra_respuesta_13_1: 0
    medioambiente_chilectra_respuesta_13_2: 0
    medioambiente_chilectra_respuesta_13_3: 0
    medioambiente_chilectra_respuesta_13_4: 0
    medioambiente_chilectra_respuesta_13_5: 0
    medioambiente_chilectra_respuesta_13_6: 0
    medioambiente_chilectra_respuesta_13_7: 0
    medioambiente_chilectra_respuesta_13_8: 0
    medioambiente_chilectra_respuesta_13_9: 0
    medioambiente_chilectra_respuesta_13_10: 0

    medioambiente_peru_obras_civiles_respuesta_13_1: 0
    medioambiente_peru_obras_civiles_respuesta_13_2: 0
    medioambiente_peru_obras_civiles_respuesta_13_3: 0
    medioambiente_peru_obras_civiles_respuesta_13_4: 0
    medioambiente_peru_obras_civiles_respuesta_13_5: 0
    medioambiente_peru_obras_civiles_respuesta_13_6: 0
    medioambiente_peru_obras_civiles_respuesta_13_7: 0
    medioambiente_peru_obras_civiles_respuesta_13_8: 0
    medioambiente_peru_obras_civiles_respuesta_13_9: 0
    medioambiente_peru_obras_civiles_respuesta_13_10: 0

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
          - 'BcTicCamIpalBundle:Default:form_bootstrap_layout.html.twig'
    globals:
        web_path: %web_path%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging: false
        profiling: false
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                CAST: BcTic\CamIpalBundle\DQL\CastFunction

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: "%mailer_disable%"
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    spool:
        type: file
        path: "%kernel.root_dir%/spool"

gregwar_image:
    cache_dir:  uploads/cache/images

simple_things_entity_audit:
    audited_entities:
      - BcTic\CamIpalBundle\Entity\Encuesta
      - BcTic\CamIpalBundle\Entity\EncuestaChilectra
      - BcTic\CamIpalBundle\Entity\EncuestaElectrica
      - BcTic\CamIpalBundle\Entity\EncuestaColombiaGeneral
      - BcTic\CamIpalBundle\Entity\EncuestaBrazilGeneral
      - BcTic\CamIpalBundle\Entity\EncuestaBrazilInterno
      - BcTic\CamIpalBundle\Entity\EncuestaLogistica
      - BcTic\CamIpalBundle\Entity\EncuestaObrasCiviles
      - BcTic\CamIpalBundle\Entity\EncuestaTelecomunicaciones
      - BcTic\CamIpalBundle\Entity\EncuestaLlvv
      - BcTic\CamIpalBundle\Entity\EncuestaFAM
      - BcTic\CamIpalBundle\Entity\EncuestaPeruElectrica
      - BcTic\CamIpalBundle\Entity\EncuestaPeruLogistica
      - BcTic\CamIpalBundle\Entity\EncuestaPeruObrasCiviles
      - BcTic\CamIpalBundle\Entity\EncuestaPeruTelecomunicaciones
      - BcTic\CamIpalBundle\Entity\Observacion
      - BcTic\CamIpalBundle\Entity\ObservacionDeComportamiento
      - BcTic\CamIpalBundle\Entity\RegistroDeObservacion
