bc_tic_cam_ipal:
    resource: "@BcTicCamIpalBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern: /login_check

logout:
    pattern: /logout

simple_things_entity_audit:
    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing.yml"
    prefix: /audit    
