security:
    encoders:
        BcTic\CamIpalBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: { class: BcTic\CamIpalBundle\Entity\Usuario, property: username }  

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: _login
                check_path: /login_check
            logout:
                path: _logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/usuario, roles: ROLE_ADMIN }
